import type { Product } from './types';

export const products: Product[] = [
  {
    id: 'classic-teddy-bear',
    name: 'Classic Teddy Bear',
    description: 'A timeless friend for all ages.',
    longDescription: 'The Classic Teddy Bear is made from super-soft, high-quality plush fabric and filled with fluffy stuffing, making it perfect for hugs. Its friendly, stitched face and classic design make it a cherished companion for years to come.',
    price: 29.99,
    images: ['teddy-bear-1', 'teddy-bear-2'],
    category: 'Bear',
    brand: 'Snuggle Originals',
    materials: '100% Polyester Plush, Recycled Stuffing',
    care: 'Surface wash with a damp cloth. Air dry.',
    ageRange: 'All Ages',
  },
  {
    id: 'flopsy-the-bunny',
    name: 'Flopsy the Bunny',
    description: 'With long floppy ears and a twitchy nose.',
    longDescription: 'Flopsy the Bunny is ready to hop into your heart. Its incredibly long and soft ears are perfect for little hands to hold, and its gentle expression makes it an instant friend. A perfect gift for Easter or a new baby.',
    price: 24.99,
    images: ['bunny-1', 'bunny-2'],
    category: 'Bunny',
    brand: 'CuddleCo',
    materials: 'Velboa Fabric, Cotton Tail',
    care: 'Machine wash cold, gentle cycle. Tumble dry low.',
    ageRange: '0+',
  },
  {
    id: 'sparkle-the-unicorn',
    name: 'Sparkle the Unicorn',
    description: 'A magical friend with a rainbow mane.',
    longDescription: 'Bring a touch of magic home with Sparkle the Unicorn. Featuring a shimmering horn, fluffy rainbow mane and tail, and sparkly hooves, Sparkle is ready for enchanting adventures. Its soft white body is perfect for snuggling after a long day of play.',
    price: 34.99,
    images: ['unicorn-1', 'unicorn-2'],
    category: 'Magical',
    brand: 'Fantasy Plush',
    materials: 'Sparkle Fabric, Polyester Plush',
    care: 'Spot clean only to protect sparkles.',
    ageRange: '3+',
  },
  {
    id: 'rex-the-dinosaur',
    name: 'Rex the Dinosaur',
    description: 'A friendly T-Rex who loves to cuddle.',
    longDescription: 'Don\'t let the "T-Rex" fool you - Rex is the friendliest dinosaur around! With soft green plush, felt teeth, and a huggable body, Rex is more about snuggles than stomping. A great companion for any dinosaur enthusiast.',
    price: 32.99,
    images: ['dinosaur-1', 'dinosaur-2'],
    category: 'Dinosaur',
    brand: 'Prehistoric Pals',
    materials: 'Minky Fabric, Felt Accents',
    care: 'Surface washable.',
    ageRange: '2+',
  },
  {
    id: 'kenzie-the-koala',
    name: 'Kenzie the Koala',
    description: 'A sleepy friend from down under.',
    longDescription: 'Kenzie the Koala is the ultimate cuddle expert. With fluffy ears and a soft, round body, Kenzie gives the best hugs. Made from premium grey plush, this koala is a wonderfully sleepy and serene friend.',
    price: 28.99,
    images: ['koala-1', 'koala-2'],
    category: 'Animal',
    brand: 'Snuggle Originals',
    materials: '100% Polyester Plush',
    care: 'Surface wash with a damp cloth.',
    ageRange: 'All Ages',
  },
  {
    id: 'leo-the-lion',
    name: 'Leo the Lion',
    description: 'The brave and cuddly king of the jungle.',
    longDescription: 'Leo the Lion rules with a soft heart. His magnificent, fluffy mane and kind eyes make him a noble and trustworthy companion. He’s ready to guard your dreams and join in on any adventure.',
    price: 31.99,
    images: ['lion-1', 'lion-2'],
    category: 'Animal',
    brand: 'CuddleCo',
    materials: 'Long-pile Plush, Polyester Fill',
    care: 'Machine wash cold, gentle cycle. Air dry mane.',
    ageRange: '3+',
  },
];
